apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-app-multi-components-repo-dolc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-app-multi-components-repo-dolc
    app.kubernetes.io/part-of: test-application
  name: python-app-multi-components-repo-dolc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-app-multi-components-repo-dolc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-app-multi-components-repo-dolc
    spec:
      containers:
      - image: python-image:latest
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
