apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman
    app.kubernetes.io/part-of: test-application
  name: pacman
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: pacman
status:
  loadBalancer: {}
